create table country
(
    id        bigint generated by default as identity,
    primary key,
    continent varchar(255),
    name      varchar(255)
);


create table author
(
    id         bigint generated by default as identity,
    primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint references country
);

create table book
(
    id               bigint generated by default as identity,
    primary key,
    available_copies integer,
    category         integer,
    times_rented     integer,
    author_id        bigint references author,
    name             varchar(255),
);

create table book_users
(
    username                   varchar(255)
        primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);
create table wishlist
(
    id            bigint generated by default as identity,
    primary key,
    date_created  timestamp,
    status        varchar(50),
    user_username varchar(255) references book_users
);
create table wishlist_books
(
    wishlist_id bigint references wishlist on delete cascade,
    books_id    bigint references book_users on delete cascade,
    primary key (wishlist_id, books_id)
);
create index idx_wishlist_user_status on wishlist (user_username, status);
create index idx_user_username_password on book_users (username, password);
create index idx_user_username on book_users (username);
create index idx_user_role on book_users (role);
